# bibliotecas usadas

In [2]:
import pandas as pd

# carregamento do csv e a primeira olhada no df

In [3]:
df = pd.read_csv('C:\Arquivos Vsco\Projeto\Projeto GS 2K26\dados_clima_bruto.csv')
df.head()

<>:1: SyntaxWarning: "\A" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\A"? A raw string is also an option.
<>:1: SyntaxWarning: "\A" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\A"? A raw string is also an option.
C:\Users\user\AppData\Local\Temp\ipykernel_3800\2754300124.py:1: SyntaxWarning: "\A" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\A"? A raw string is also an option.
  df = pd.read_csv('C:\Arquivos Vsco\Projeto\Projeto GS 2K26\dados_clima_bruto.csv')

          data_hora  temperatura  umidade  precipitacao     cidade
0  2026-05-23T00:00         14.4       97           0.0  Sao_Paulo
1  2026-05-23T01:00         14.6       97           0.0  Sao_Paulo
2  2026-05-23T02:00         14.8       97           0.0  Sao_Paulo
3  2026-05-23T03:00         14.7       97           0.0  Sao_Paulo
4  2026-05-23T04:00         14.5       98           0.0  Sao_Paulo

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1008 entries, 0 to 1007
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   data_hora     1008 non-null   object
 1   temperatura   1008 non-null   float64
 2   umidade       1008 non-null   int64
 3   precipitacao  1008 non-null   float64
 4   cidade        1008 non-null   object
dtypes: float64(2), int64(1), object(2)
memory usage: 39.5+ KB

In [5]:
df.describe()

       temperatura      umidade  precipitacao
count  1008.000000  1008.000000   1008.000000
mean     16.009524    86.490079      0.138790
std       2.954892    12.974725      0.673158
min      10.100000    47.000000      0.000000
25%      13.900000    78.750000      0.000000
50%      15.600000    92.000000      0.000000
75%      18.000000    97.000000      0.000000
max      25.800000   100.000000      9.000000

# verificando se tem valores nulos ou duplicados

In [6]:
df.isnull().sum()

data_hora       0
temperatura     0
umidade         0
precipitacao    0
cidade          0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

# tratando a variável de data_hora

In [8]:
df['data_hora'] = pd.to_datetime(df['data_hora'])

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1008 entries, 0 to 1007
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   data_hora     1008 non-null   datetime64[ns]
 1   temperatura   1008 non-null   float64
 2   umidade       1008 non-null   int64
 3   precipitacao  1008 non-null   float64
 4   cidade        1008 non-null   object
dtypes: datetime64[ns](1), float64(2), int64(1), object(1)
memory usage: 39.5+ KB

# salvando o df

In [9]:
df.to_csv('dados_clima_tratados')